### ISSUE TITLE
password

### ISSUE THREAD

**Issue by Jogala** [arvindr226/alpine-ssh#5]
I did 

`docker build --build-arg PASSWORD=jo -t sshcont -f Dockerfile .`

But when I get promted for the password 

```
ssh root@localhost -p 2222
root@localhost's password: 
```

Typing jo as password does not work.

What to do??? :(

**Comment by arvindr226** [comment]
Step 1: Build the docker image.
`docker build --build-arg PASSWORD=jo -t sshcont -f Dockerfile .`

Step 2: Run the docker container
`docker run -d -p 2222:22 sshcont`

Step 3: try to login using ssh client
`ssh root@localhost -p 2222`

I verified again with `jo` password, its working for me. 
if still facing issue please provide me the logs of `ssh -v root@localhost`
